name = "mp3_parser"
description = "Shiny new project"
version = "0.0.0"

authors = ["Anuj Seth"]
maintainers = ["Anuj Seth <anujseth76@gmail.com>"]
maintainers-logins = ["anuj-seth"]

executables = ["mp3_parser"]
